fix action

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -1,15 +1,17 @@
 on:
   schedule:
-    - cron:  '40 10,15,21 * * *'
+    - cron:  '31 10,16,21 * * *'
   push:
-    branches: [master]
+    branches: [main]
+
 jobs:
-  job1:
+  update:
     runs-on: ubuntu-latest
 
     steps:
       - uses: actions/checkout@v2
-        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
+        with:
+          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
 
       - name: Use Node.js
         uses: actions/setup-node@v2
@@ -19,16 +21,14 @@ jobs:
       - name: Update data
         run: npm install && npm run fetch
 
-      - name: Check state
-        run: "[[ -n $(git status --porcelain --untracked-files=no) ]] && touch .is-dirty"
-
       - name: Commit files
-        if: hashFiles('.is-dirty') != ''
         run: |
           git config --local user.email "action@github.com"
           git config --local user.name "GitHub Action"
           git add .
-          git commit -m "Update data" -a
+          ([[ -n $(git status --porcelain) ]] && git commit -m "Update data" -a) || echo "nothing to commit"
 
-    - name: Push changes
-      uses: ad-m/github-push-action@master
+      - name: Push changes
+        uses: ad-m/github-push-action@master
+        with:
+          github_token: ${{ secrets.GITHUB_TOKEN }}
